---
title: christopherson.io
description: Zach's thoughts on data analytics and visualization cloud technologies.
baseurl: 
url: http://christopherson.io
username: Zach Christopherson
user_title: Zach Christopherson - Senior Amazon Redshift Database Engineer
email: zach@christopherson.io
twitter_username: zach_data
github_username: zach-data
linkedin_username: zachchristopherson
gplus_username: 
disqus_username: 
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
links:
- title: home
  url: "/"
- title: my posts
  url: "/posts"
- title: series
  url: "/series"
- title: tags
  url: "/tags"
- title: about me
  url: "/about"
projects:
- name: amazon-redshift-utils
  url: https://github.com/awslabs/amazon-redshift-utils
- name: amazon-redshift-udfs
  url: https://github.com/awslabs/amazon-redshift-udfs
- name: amazon-redshift-monitoring
  url: https://github.com/awslabs/amazon-redshift-monitoring/tree/realtime
exclude:
- package.json
- src
- node_modules
